apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
{{ toYaml .Values.nginx.resources | indent 10 }}
        args:
        - /nginx-ingress-controller
        - --default-backend-service={{ .Release.Namespace }}/nginx-default-backend