apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.nginx.service.type | quote }}
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: {{ app.name}} #when we are deploying a application we map the app name here